### ISSUE TITLE
TYPO3 8 CMS compatibility

### ISSUE THREAD

**Issue by taalas** [derhansen/sf_yubikey#36]
Is the current version compatible with TYPO3 8 and/or do you plan to add this?

**Comment by derhansen** [comment]
Yes, current version is compatible to TYPO3 8.7 and released on TER / Packagist on 26.02.2017. 

Any problems with this version on V8?

**Comment by taalas** [comment]
No, sorry. I might have misread the dependency information. Looking forward to giving the extension a try ;)
